
_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/ppyoloe_reader.yml',
]


# optimizer
epoch: &epoch 300
use_fused_allreduce_gradients: &use_checkpoint False

LearningRate:
  base_lr: 0.0001
  schedulers:
    - !CosineDecay
      max_epochs: *epoch
    - !LinearWarmup
      start_factor: 0.
      epochs: 5

OptimizerBuilder:
  optimizer:
    type: AdamWDL
    betas: [0.9, 0.999]
    layer_decay: 0.75
    weight_decay: 0.05 # 0.02
    num_layers: 12
    filter_bias_and_bn: True
    skip_decay_names: ['pos_embed', 'cls_token']
    set_param_lr_func: 'layerwise_lr_decay'


# reader
TrainReader:
  batch_size: 2


# model
architecture: YOLOv3
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: VisionTransformer
  neck: YOLOCSPPAN # CustomCSPPAN
  yolo_head: PPYOLOEHead
  post_process: ~


VisionTransformer:
  patch_size: 16
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4
  qkv_bias: True
  drop_rate: 0.0
  drop_path_rate: 0.2
  init_values: 0.1
  final_norm: False
  use_rel_pos_bias: False
  use_sincos_pos_emb: True
  epsilon: 0.000001 # 1e-6
  out_indices: [5, 7, 11]
  with_fpn: True
  use_checkpoint: *use_checkpoint
  pretrained: https://bj.bcebos.com/v1/paddledet/models/pretrained/vit_base_cae_pretrained.pdparams



YOLOCSPPAN:
  depthwise: False
  in_channels: [768, 768, 768]
  act: 'silu'


# CustomCSPPAN:
#   out_channels: [768, 384, 192]
#   stage_num: 1
#   block_num: 3
#   act: 'swish'
#   spp: true


PPYOLOEHead:
  fpn_strides: [8, 16, 32]
  in_channels: [768, 768, 768]
  grid_cell_scale: 5.0
  grid_cell_offset: 0.5
  static_assigner_epoch: 100
  use_varifocal_loss: True
  loss_weight: {class: 1.0, iou: 2.5, dfl: 0.5}
  static_assigner:
    name: ATSSAssigner
    topk: 9
  assigner:
    name: TaskAlignedAssigner
    topk: 13
    alpha: 1.0
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 300
    score_threshold: 0.01
    nms_threshold: 0.7
