_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/dino_r50.yml',
  '_base_/dino_reader.yml',
]

weights: output/dini_r50_4_1_6_coco/model_final
find_unused_parameters: True
log_iter: 100


ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.1, 0.1, 0.1, 0.1]
  num_stages: 4
  freeze_stem_only: true


DINOTransformer:
  num_levels: 4
  num_encoder_layers: 1
  num_decoder_layers: 6
