_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_5x.yml',
  '_base_/dino_r50.yml',
  # '_base_/dino_640_reader.yml',
  '_base_/yoloe_reader.yml',
]

weights: output/dino_r50_640_pan_4_0_6_3x_coco_reader_enhance/model_final
find_unused_parameters: True
log_iter: 100


pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_v2_pretrained.pdparams
norm_type: sync_bn
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"



DETR:
  backbone: ResNet
  neck: YOLOCSPPAN
  transformer: DINOTransformer
  detr_head: DINOHead
  post_process: DETRBBoxPostProcess


ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.1, 0.1, 0.1, 0.1]
  num_stages: 4
  freeze_stem_only: true
  variant: d


YOLOCSPPAN:
  depthwise: False
  use_trans: True
  nhead: 8
  num_layers: 2 # 3
  dim_feedforward: 2048
  dropout: 0.1
  activation: 'gelu'
  proj_dim: [512, 512, 512]


# YOLOCSPPAN:
#   depthwise: False
#   # act: 'relu'

# FPN:
#   out_channel: 256

DINOTransformer:
  num_queries: 300 # 900
  position_embed_type: sine
  num_levels: 4 # 3
  nhead: 8
  num_encoder_layers: 0
  num_decoder_layers: 6
  dim_feedforward: 2048
  dropout: 0.0
  activation: relu # gelu
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  learnt_init_query: True


DINOHead:
  loss:
    name: DINOLoss
    loss_coeff: {class: 1, bbox: 5, giou: 2}
    aux_loss: True
    use_vfl: True
    matcher:
      name: HungarianMatcher
      matcher_coeff: {class: 2, bbox: 5, giou: 2}
      use_pos_only: True


DETRBBoxPostProcess:
  num_top_queries: 300
