_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_3x.yml',
  '_base_/dino_r50.yml',
  '_base_/dino_640_reader.yml',
  # '_base_/yoloe_reader.yml',
]

weights: output/dino_r50_640_fpn_4_0_6_3x_coco/model_final
find_unused_parameters: True
log_iter: 100

DETR:
  backbone: ResNet
  neck: FPN
  transformer: DINOTransformer
  detr_head: DINOHead
  post_process: DETRBBoxPostProcess



ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.1, 0.1, 0.1, 0.1]
  num_stages: 4
  freeze_stem_only: true


FPN:
  out_channel: 256


DINOTransformer:
  num_queries: 900
  position_embed_type: sine
  num_levels: 4
  nhead: 8
  num_encoder_layers: 0
  num_decoder_layers: 6
  dim_feedforward: 2048
  dropout: 0.0
  activation: relu
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  learnt_init_query: True
