_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/dino_r50vd_pan.yml',
  '_base_/yoloe_reader.yml',
]

weights: output/ppdetr_r50_6x_coco/model_final
find_unused_parameters: True
log_iter: 100
snapshot_epoch: 1


ResNet:
  # index 0 stands for res2
  depth: 50
  variant: d
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.1, 0.1, 0.1, 0.1]
  # lr_mult_list: [0.01, 0.01, 0.01, 0.01]

  num_stages: 4
  freeze_stem_only: True


epoch: 72

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 1.0
    milestones: [100]
    use_warmup: true
  - !LinearWarmup
    start_factor: 0.001
    steps: 2000

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
