_BASE_: [
  '../runtime.yml',
  # './lst_dataset.yml',
  './lst_obj365.yml',
  '../ppyoloe/_base_/ppyoloe_crn.yml',
]
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_l_pretrained.pdparams

use_ema: true
ema_decay: 0.9998


log_iter: 100
snapshot_epoch: 10
weights: output/lst_yoloe_l_3x/model_final

depth_mult: 1.0
width_mult: 1.0


PPYOLOEHead:
  fpn_strides: [32, 16, 8]
  grid_cell_scale: 5.0
  grid_cell_offset: 0.5
  static_assigner_epoch: 20  # epoch/3
  use_varifocal_loss: True
  loss_weight: {class: 1.0, iou: 2.5, dfl: 0.5}
  static_assigner:
    name: ATSSAssigner
    topk: 9
  assigner:
    name: TaskAlignedAssigner
    topk: 13
    alpha: 1.0
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.01
    nms_threshold: 0.6


epoch: 60

LearningRate:
  base_lr: 0.01
  schedulers:
    - !CosineDecay
      max_epochs: 72 # + 1/5
    - !LinearWarmup
      start_factor: 0.
      epochs: 1 # 60


OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

# epoch: 120
# LearningRate:
#   base_lr: 0.01  # 4 * 16x8 - > 0.08 (nan)
#   schedulers:
#     - !CosineDecay
#       max_epochs: 144 # + 1/5
#     - !LinearWarmup
#       start_factor: 0.
#       epochs: 2


# OptimizerBuilder:
#   optimizer:
#     momentum: 0.9
#     type: Momentum
#   regularizer:
#     factor: 0.0005
#     type: L2


# epoch: 36 # 24 # 36 53-day
# LearningRate:
#   # base_lr: 0.005 # 0.0075
#   base_lr: 0.00333 # 0.0075  8 vs 12
#   schedulers:
#   - !PiecewiseDecay
#     gamma: 0.1
#     milestones:
#     - 24 # 16 # 24
#   - !LinearWarmup
#     start_factor: 0.
#     steps: 10000

# OptimizerBuilder:
#   clip_grad_by_norm: 35.
#   optimizer:
#     momentum: 0.9
#     type: Momentum
#   regularizer:
#     factor: 0.0005
#     type: L2
