_BASE_: [
  '../runtime.yml',
  '../picodet/picodet_xs_320_coco_lcnet.yml',
  './lst_dataset_obj365.yml',
]



log_iter: 100
snapshot_epoch: 10
weights: output/lst_picodet_xs_320_60e/model_final

PicoHeadV2:
  static_assigner_epoch: 20


epoch: 60

TrainReader:
  batch_size: 64

LearningRate:
  base_lr: 0.32
  schedulers:
  - !CosineDecay
    max_epochs: 60
  - !LinearWarmup
    start_factor: 0.1
    epochs: 1 # 60
