epoch: 36


# for backbone
LearningRate1:
  base_lr: 0.01
  schedulers:
  - !CosineDecay
    max_epochs: *epoch
    min_lr_ratio: 0.05
  - !LinearWarmup
    start_factor: 0.001
    steps: 2000

OptimizerBuilder1:
  optimizer:
    type: Momentum
    momentum: 0.9
    use_nesterov: True
  regularizer:
    factor: 0.0005
    type: L2



# for neck
LearningRate2:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [100]
    # use_warmup: false
  - !LinearWarmup
    start_factor: 0.001
    steps: 2000

OptimizerBuilder2:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001


# for transformer
LearningRate3:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [100]
    # use_warmup: false
  - !LinearWarmup
    start_factor: 0.001
    steps: 2000

OptimizerBuilder3:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
