
epoch: 60

# LearningRate:
#   base_lr: 0.0001
#   schedulers:
#   - !PiecewiseDecay
#     gamma: 0.1
#     milestones: [27, 33]
#     use_warmup: false

LearningRate:
  base_lr: 0.0001
  schedulers:
    - !CosineDecay
      max_epochs: 60
      min_lr_ratio: 0.01
    - !LinearWarmup
      start_factor: 0.001
      epochs: 1


OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
